### PR TITLE
User/gundermanc/database core. Addresses issue #6.

### PR DESCRIPTION
**Pull request by gundermanc**
Configured servlet for MySQL JDBC connection pool, wrote Java code for obtaining a SQL connection and operating on it safely, and wrote scripts for installing database schemata on OS X and Windows, updated README, and modified OSS scripts to copy MySQL-connector-java.jar to the tomcat libs directory.

@hschmack @et8109 This is the code that you can use to create your tables once we have it in the features/database_core branch you can work on branches off of there.

### CODE REVIEW

**Comment by ghost** [comment]
so I see the raw sql file that creates the database from the oss script, but how will we create the tables? Just add them to the sql file?

**Comment by gundermanc** [comment]
Yeah just add a file for your tables and link to it from the main one

**Comment by ghost** [comment]
@gundermanc 
can you just let me know if this is what you were thinking with the sqlinterface?
http://pastebin.com/DZqHevzd

**Comment by hschmack** [comment]
@et8109, @gundermanc  let me know if that's what you had in mind. I have something similar for the File table

**Comment by ghost** [comment]
Christian said the plan was to create an anonymous sqlinteractioninterface which then calls the datatier  functions inside run, passing the connection. So what I have doesn't fit into that.

**Comment by gundermanc** [comment]
@et8109 @hschmack So I updated it, what I am going for is something like this:
In the REST APIs and JSP pages you have code like this: https://github.com/CatalystOfNostalgia/feckless-weasel/blob/user/gundermanc/user_auth/service/src/main/java/com/fecklessweasel/service/api/v1/Users1Resource.java 

That code calls the Object Model layer code, which looks like this: https://github.com/CatalystOfNostalgia/feckless-weasel/blob/user/gundermanc/user_auth/service/src/main/java/com/fecklessweasel/service/objectmodel/User.java

That code has most error checking and stuff and represents the object, the user in this case, an entity within the website. The actual SQL calls are done in code in the datatier:
https://github.com/CatalystOfNostalgia/feckless-weasel/blob/user/gundermanc/user_auth/service/src/main/java/com/fecklessweasel/service/datatier/UserTable.java

**Pull request merged**
